apiVersion: apps/v1
kind: Deployment
metadata:
  name: MavenCICD
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      name: mavencicdpod
      labels:
        app: maven
    spec:
      containers:
      - name: mavencicdcontainer
        image: samuelpolagani98/maven-web:BUILDNUM
        ports:
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavencicdservice
  namespace: test-ns
spec:
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
