apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavencicd
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      name: mavencicdpod
      labels:
        app: maven
    spec:
      containers:
      - name: mavencicdcontainer
        image: 237277575225.dkr.ecr.ap-south-2.amazonaws.com/maven-web:BUILDNUM
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavencicdservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
